# This is a basic workflow to help you get started with Actions

name: CI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Validate-Design-on-SwaggerHub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node -version: "12.x"
      - name : Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name : Check the API definition exists
        env:
          SWAGGER_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:get Demo_DR1/payment-pre_authorisation_api/1.0
      - name: Validate definition
        env:
          SWAGGER_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:validate Demo_DR1/payment-pre_authorisation_api/1.0

